### ISSUE TITLE
The JavaScript option needs to be added back

### ISSUE THREAD

**Issue by carolinan** [cyberchimps/responsive#93]
Hi
It seems that somewhere between version 4.0.5 and 4.1.0-beta.4
the option to add JavaScript in the footer and header has been removed?

I have not been able to find any documentation about this on your website.
This is going to break websites further, on top of everything you have already changed.

I know that adding JS this way is not optimal. We do not allow new themes that are added to the WordPress.org theme directory to include these kind of options.
But you are going to break websites in ways that are beyond repair for many users.

**Comment by ratnesh-kadam** [comment]
@carolinan 
We have intentionally removed the option to add Javascript in the footer and header as this functionality should not be the part of the theme. We have plan to move this functionality to the free plugin.

**Comment by carolinan** [comment]
Who is going to compensate site builders who has to spend time sorting this out? The conversion has already cost my client 7 over hours work.  This update has been out of control.

**Comment by ratnesh-kadam** [comment]
@carolinan 
We agree with what you are saying. We will add the option to add Javascript in the footer and header.
